import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Index.module.css";
import { useState } from "react";
import Dashboard from "../components/Dashboard";
import Search from "../components/Search";

const inter = Inter({ subsets: ["latin"] });

export default function Index() {
  const [activeMenu, setActiveMenu] = useState("Dashboard");
  const [user, setUser] = useState([]);

  // function to logout from application
  const logoutHandler = () => {
    console.log("LOGOUT");
  };

  return (
    <>
      <Head>
        <title>Dashboard - SIPEDAMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sidebar}>
          <div class={styles.profile}>
            <Image />
            <ul className={styles.profileContainerList}>
              <li
                style={{
                  fontSize: "21px",
                  listStyle: "none",
                  fontWeight: "normal",
                }}
              >
                Farhan Agustiansyah
              </li>
              <li
                style={{
                  fontSize: "16px",
                  listStyle: "none",
                  fontWeight: "lighter",
                  color: "#9599A6",
                }}
              >
                Administrator App
              </li>
            </ul>
          </div>
          <div className={styles.menu}>
            <ul className={styles.menuContainerList}>
              <li
                className={styles.menuItem}
                onClick={(e) => {
                  setActiveMenu("Dashboard");
                }}
                style={
                  activeMenu == "Dashboard"
                    ? { color: "#83D887" }
                    : { color: "#FFFFFF" }
                }
              >
                Dashboard
              </li>
              <li
                className={styles.menuItem}
                onClick={(e) => {
                  setActiveMenu("Search");
                }}
                style={
                  activeMenu == "Search"
                    ? { color: "#83D887" }
                    : { color: "#FFFFFF" }
                }
              >
                Search
              </li>
            </ul>
          </div>
          <button className={styles.btn} onClick={logoutHandler}>
            Log Out
          </button>
        </div>
        <div className={styles.content}>
          {activeMenu == "Dashboard" ? <Dashboard /> : <Search />}
        </div>
      </main>
    </>
  );
}
