import Head from "next/head";
import React from "react";
import styles from "../styles/Login.module.css";

function Login() {
  return (
    <>
      <Head>
        <title>Login - SIPEDAMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.text}>LOGIN</h1>
      </main>
    </>
  );
}

export default Login;
