import Head from "next/head";
import React from "react";
import styles from "../styles/Login.module.css";

function Login() {
  return (
    <>
      <Head>
        <title>Login - SIPEDAMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.loginInnerContainer}>
          <img src="https://i.postimg.cc/L5hQM7Dw/graduation.png" />
          <h1 style={{ color: "#020b2a", marginTop: "-2rem" }}>
            Sign in to <br />
            Sistem Pengelola Data Mahasiswa
          </h1>
          <p style={{ color: "#020b2a" }}>by farhanaugustiansyah</p>

          <button className={styles.btn}>Sign in</button>
        </div>
      </main>
    </>
  );
}

export default Login;
